apiVersion: apps/v1
kind: Deployment

metadata:
  name: message-service-deployment
  namespace: devops

spec:
  replicas: 1

  selector:
    matchLabels:
      app: message-service

  template:

    metadata:
      labels:
        app: message-service

    spec:
      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: message-service-container
#          image: message-service:1.0
          image: ghcr.io/jazibeqbal/microservices-devops/message-service:4d1b17b92d661b26cd823b4f98e0d4f09fa2bbf6
          ports:
            - containerPort: 9000

          readinessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 5

          volumeMounts:
            - name: message-data
              mountPath: /data

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "256Mi"

#      volumes:
#        - name: message-data
#          emptyDir: {}
      volumes:
        - name: message-data
          persistentVolumeClaim:
            claimName: message-data-pvc