name: CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Kubernetes
        run: |
          kubectl get nodes

      - name: Deploy application
        run: |
          chmod +x scripts/deploy.sh
          chmod +x scripts/smoke-test.sh
          ./scripts/deploy.sh 4d1b17b92d661b26cd823b4f98e0d4f09fa2bbf6