name: CD

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Kubernetes
        run: |
          kubectl get nodes

      - name: Deploy application
        run: |
          chmod +x scripts/deploy.sh
          ./scripts/deploy.sh ${{ github.event.workflow_run.head_sha }}

      - name: Get API URL
        run: |
          API_URL=$(minikube service api-svc -n devops --url)
          echo "API_URL=$API_URL" >> "$GITHUB_ENV"

      - name: Run smoke tests
        run: |
          chmod +x scripts/smoke-test.sh
          ./scripts/smoke-test.sh