name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build APP Image
        run: docker build -t devops-app:1.0 .

      - name: Build Message Service Image
        run: docker build -t message-service:1.0 ./message-service/

      - name: Build Food Service Image
        run: docker build -t food-service:1.0 ./food-service/