name: CI

on:
  push:
    branches:
      - dev

#  pull_request:
#    branches:
#      - main

permissions:
  contents: read
  packages: write

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

  build:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Image Name
        run: |
          IMAGE_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME=ghcr.io/$IMAGE_NAME" >> "$GITHUB_ENV"

      - name: Build API Image
        run: |
          docker build -t "$IMAGE_NAME/devops-app:${{ github.sha }}" .

      - name: Build Message Service Image
        run: |
          docker build -t "$IMAGE_NAME/message-service:${{ github.sha }}" ./message-service/

      - name: Build Food Service Image
        run: |
          docker build -t "$IMAGE_NAME/food-service:${{ github.sha }}" ./food-service/
          
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Images
        run: |
          docker push "$IMAGE_NAME/devops-app:${{ github.sha }}"
          docker push "$IMAGE_NAME/message-service:${{ github.sha }}"
          docker push "$IMAGE_NAME/food-service:${{ github.sha }}"